// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ForceMenu","status":true,"description":"強制メニュー表示","parameters":{}},
{"name":"SetupOptionCustomize","status":true,"description":"起動オプション調整プラグイン","parameters":{"描画モード":"0","テストプレー":"ON","FPS表示":"ON","オーディオ無効":"OFF","任意オプション":"","ユーザオプション無効":"OFF"}}
];
